#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Li_Tiem_Net
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLi Tiem Net")]
	public partial class databaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDoUong(DoUong instance);
    partial void UpdateDoUong(DoUong instance);
    partial void DeleteDoUong(DoUong instance);
    partial void InsertGoiChoi(GoiChoi instance);
    partial void UpdateGoiChoi(GoiChoi instance);
    partial void DeleteGoiChoi(GoiChoi instance);
    partial void InsertListSP(ListSP instance);
    partial void UpdateListSP(ListSP instance);
    partial void DeleteListSP(ListSP instance);
    partial void InsertMonAn(MonAn instance);
    partial void UpdateMonAn(MonAn instance);
    partial void DeleteMonAn(MonAn instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public databaseDataContext() : 
				base(global::Quan_Li_Tiem_Net.Properties.Settings.Default.QLi_Tiem_NetConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DoUong> DoUongs
		{
			get
			{
				return this.GetTable<DoUong>();
			}
		}
		
		public System.Data.Linq.Table<GoiChoi> GoiChois
		{
			get
			{
				return this.GetTable<GoiChoi>();
			}
		}
		
		public System.Data.Linq.Table<ListSP> ListSPs
		{
			get
			{
				return this.GetTable<ListSP>();
			}
		}
		
		public System.Data.Linq.Table<MonAn> MonAns
		{
			get
			{
				return this.GetTable<MonAn>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoUong")]
	public partial class DoUong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDoUong;
		
		private string _TenDoUong;
		
		private string _GiaTien;
		
		private EntitySet<ListSP> _ListSPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDoUongChanging(string value);
    partial void OnMaDoUongChanged();
    partial void OnTenDoUongChanging(string value);
    partial void OnTenDoUongChanged();
    partial void OnGiaTienChanging(string value);
    partial void OnGiaTienChanged();
    #endregion
		
		public DoUong()
		{
			this._ListSPs = new EntitySet<ListSP>(new Action<ListSP>(this.attach_ListSPs), new Action<ListSP>(this.detach_ListSPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoUong", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDoUong
		{
			get
			{
				return this._MaDoUong;
			}
			set
			{
				if ((this._MaDoUong != value))
				{
					this.OnMaDoUongChanging(value);
					this.SendPropertyChanging();
					this._MaDoUong = value;
					this.SendPropertyChanged("MaDoUong");
					this.OnMaDoUongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDoUong", DbType="NVarChar(50)")]
		public string TenDoUong
		{
			get
			{
				return this._TenDoUong;
			}
			set
			{
				if ((this._TenDoUong != value))
				{
					this.OnTenDoUongChanging(value);
					this.SendPropertyChanging();
					this._TenDoUong = value;
					this.SendPropertyChanged("TenDoUong");
					this.OnTenDoUongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="NVarChar(50)")]
		public string GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoUong_ListSP", Storage="_ListSPs", ThisKey="MaDoUong", OtherKey="MaDoUong")]
		public EntitySet<ListSP> ListSPs
		{
			get
			{
				return this._ListSPs;
			}
			set
			{
				this._ListSPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ListSPs(ListSP entity)
		{
			this.SendPropertyChanging();
			entity.DoUong = this;
		}
		
		private void detach_ListSPs(ListSP entity)
		{
			this.SendPropertyChanging();
			entity.DoUong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GoiChoi")]
	public partial class GoiChoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGoi;
		
		private string _TenGoi;
		
		private string _GiaTien;
		
		private EntitySet<ListSP> _ListSPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGoiChanging(string value);
    partial void OnMaGoiChanged();
    partial void OnTenGoiChanging(string value);
    partial void OnTenGoiChanged();
    partial void OnGiaTienChanging(string value);
    partial void OnGiaTienChanged();
    #endregion
		
		public GoiChoi()
		{
			this._ListSPs = new EntitySet<ListSP>(new Action<ListSP>(this.attach_ListSPs), new Action<ListSP>(this.detach_ListSPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGoi", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGoi
		{
			get
			{
				return this._MaGoi;
			}
			set
			{
				if ((this._MaGoi != value))
				{
					this.OnMaGoiChanging(value);
					this.SendPropertyChanging();
					this._MaGoi = value;
					this.SendPropertyChanged("MaGoi");
					this.OnMaGoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGoi", DbType="NVarChar(50)")]
		public string TenGoi
		{
			get
			{
				return this._TenGoi;
			}
			set
			{
				if ((this._TenGoi != value))
				{
					this.OnTenGoiChanging(value);
					this.SendPropertyChanging();
					this._TenGoi = value;
					this.SendPropertyChanged("TenGoi");
					this.OnTenGoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="NVarChar(50)")]
		public string GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GoiChoi_ListSP", Storage="_ListSPs", ThisKey="MaGoi", OtherKey="MaMonAn")]
		public EntitySet<ListSP> ListSPs
		{
			get
			{
				return this._ListSPs;
			}
			set
			{
				this._ListSPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ListSPs(ListSP entity)
		{
			this.SendPropertyChanging();
			entity.GoiChoi = this;
		}
		
		private void detach_ListSPs(ListSP entity)
		{
			this.SendPropertyChanging();
			entity.GoiChoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ListSP")]
	public partial class ListSP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_San_Pham;
		
		private string _MaMonAn;
		
		private string _MaDoUong;
		
		private string _MaGoiChoi;
		
		private EntityRef<DoUong> _DoUong;
		
		private EntityRef<GoiChoi> _GoiChoi;
		
		private EntityRef<MonAn> _MonAn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_San_PhamChanging(string value);
    partial void OnID_San_PhamChanged();
    partial void OnMaMonAnChanging(string value);
    partial void OnMaMonAnChanged();
    partial void OnMaDoUongChanging(string value);
    partial void OnMaDoUongChanged();
    partial void OnMaGoiChoiChanging(string value);
    partial void OnMaGoiChoiChanged();
    #endregion
		
		public ListSP()
		{
			this._DoUong = default(EntityRef<DoUong>);
			this._GoiChoi = default(EntityRef<GoiChoi>);
			this._MonAn = default(EntityRef<MonAn>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ID San Pham]", Storage="_ID_San_Pham", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_San_Pham
		{
			get
			{
				return this._ID_San_Pham;
			}
			set
			{
				if ((this._ID_San_Pham != value))
				{
					this.OnID_San_PhamChanging(value);
					this.SendPropertyChanging();
					this._ID_San_Pham = value;
					this.SendPropertyChanged("ID_San_Pham");
					this.OnID_San_PhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMonAn", DbType="NVarChar(50)")]
		public string MaMonAn
		{
			get
			{
				return this._MaMonAn;
			}
			set
			{
				if ((this._MaMonAn != value))
				{
					if ((this._GoiChoi.HasLoadedOrAssignedValue || this._MonAn.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMonAnChanging(value);
					this.SendPropertyChanging();
					this._MaMonAn = value;
					this.SendPropertyChanged("MaMonAn");
					this.OnMaMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoUong", DbType="NVarChar(50)")]
		public string MaDoUong
		{
			get
			{
				return this._MaDoUong;
			}
			set
			{
				if ((this._MaDoUong != value))
				{
					if (this._DoUong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDoUongChanging(value);
					this.SendPropertyChanging();
					this._MaDoUong = value;
					this.SendPropertyChanged("MaDoUong");
					this.OnMaDoUongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGoiChoi", DbType="NVarChar(50)")]
		public string MaGoiChoi
		{
			get
			{
				return this._MaGoiChoi;
			}
			set
			{
				if ((this._MaGoiChoi != value))
				{
					this.OnMaGoiChoiChanging(value);
					this.SendPropertyChanging();
					this._MaGoiChoi = value;
					this.SendPropertyChanged("MaGoiChoi");
					this.OnMaGoiChoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoUong_ListSP", Storage="_DoUong", ThisKey="MaDoUong", OtherKey="MaDoUong", IsForeignKey=true)]
		public DoUong DoUong
		{
			get
			{
				return this._DoUong.Entity;
			}
			set
			{
				DoUong previousValue = this._DoUong.Entity;
				if (((previousValue != value) 
							|| (this._DoUong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DoUong.Entity = null;
						previousValue.ListSPs.Remove(this);
					}
					this._DoUong.Entity = value;
					if ((value != null))
					{
						value.ListSPs.Add(this);
						this._MaDoUong = value.MaDoUong;
					}
					else
					{
						this._MaDoUong = default(string);
					}
					this.SendPropertyChanged("DoUong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GoiChoi_ListSP", Storage="_GoiChoi", ThisKey="MaMonAn", OtherKey="MaGoi", IsForeignKey=true)]
		public GoiChoi GoiChoi
		{
			get
			{
				return this._GoiChoi.Entity;
			}
			set
			{
				GoiChoi previousValue = this._GoiChoi.Entity;
				if (((previousValue != value) 
							|| (this._GoiChoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GoiChoi.Entity = null;
						previousValue.ListSPs.Remove(this);
					}
					this._GoiChoi.Entity = value;
					if ((value != null))
					{
						value.ListSPs.Add(this);
						this._MaMonAn = value.MaGoi;
					}
					else
					{
						this._MaMonAn = default(string);
					}
					this.SendPropertyChanged("GoiChoi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonAn_ListSP", Storage="_MonAn", ThisKey="MaMonAn", OtherKey="MaMonAn", IsForeignKey=true)]
		public MonAn MonAn
		{
			get
			{
				return this._MonAn.Entity;
			}
			set
			{
				MonAn previousValue = this._MonAn.Entity;
				if (((previousValue != value) 
							|| (this._MonAn.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MonAn.Entity = null;
						previousValue.ListSPs.Remove(this);
					}
					this._MonAn.Entity = value;
					if ((value != null))
					{
						value.ListSPs.Add(this);
						this._MaMonAn = value.MaMonAn;
					}
					else
					{
						this._MaMonAn = default(string);
					}
					this.SendPropertyChanged("MonAn");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonAn")]
	public partial class MonAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMonAn;
		
		private string _TenMonAn;
		
		private string _GiaTien;
		
		private EntitySet<ListSP> _ListSPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMonAnChanging(string value);
    partial void OnMaMonAnChanged();
    partial void OnTenMonAnChanging(string value);
    partial void OnTenMonAnChanged();
    partial void OnGiaTienChanging(string value);
    partial void OnGiaTienChanged();
    #endregion
		
		public MonAn()
		{
			this._ListSPs = new EntitySet<ListSP>(new Action<ListSP>(this.attach_ListSPs), new Action<ListSP>(this.detach_ListSPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMonAn", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMonAn
		{
			get
			{
				return this._MaMonAn;
			}
			set
			{
				if ((this._MaMonAn != value))
				{
					this.OnMaMonAnChanging(value);
					this.SendPropertyChanging();
					this._MaMonAn = value;
					this.SendPropertyChanged("MaMonAn");
					this.OnMaMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMonAn", DbType="NVarChar(50)")]
		public string TenMonAn
		{
			get
			{
				return this._TenMonAn;
			}
			set
			{
				if ((this._TenMonAn != value))
				{
					this.OnTenMonAnChanging(value);
					this.SendPropertyChanging();
					this._TenMonAn = value;
					this.SendPropertyChanged("TenMonAn");
					this.OnTenMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="NVarChar(50)")]
		public string GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MonAn_ListSP", Storage="_ListSPs", ThisKey="MaMonAn", OtherKey="MaMonAn")]
		public EntitySet<ListSP> ListSPs
		{
			get
			{
				return this._ListSPs;
			}
			set
			{
				this._ListSPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ListSPs(ListSP entity)
		{
			this.SendPropertyChanging();
			entity.MonAn = this;
		}
		
		private void detach_ListSPs(ListSP entity)
		{
			this.SendPropertyChanging();
			entity.MonAn = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _LoaiTaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnLoaiTaiKhoanChanging(string value);
    partial void OnLoaiTaiKhoanChanged();
    #endregion
		
		public TaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTaiKhoan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiTaiKhoan
		{
			get
			{
				return this._LoaiTaiKhoan;
			}
			set
			{
				if ((this._LoaiTaiKhoan != value))
				{
					this.OnLoaiTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._LoaiTaiKhoan = value;
					this.SendPropertyChanged("LoaiTaiKhoan");
					this.OnLoaiTaiKhoanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
