<?xml version="1.0" encoding="utf-8"?><Database Name="QLi Tiem Net" Class="databaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-7LPD0GBV;Initial Catalog=&quot;QLi Tiem Net&quot;;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="Quan_Li_Tiem_Net.Properties.Settings" SettingsPropertyName="QLi_Tiem_NetConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DoUong" Member="DoUongs">
    <Type Name="DoUong">
      <Column Name="MaDoUong" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDoUong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaTien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DoUong_ListSP" Member="ListSPs" ThisKey="MaDoUong" OtherKey="MaDoUong" Type="ListSP" />
    </Type>
  </Table>
  <Table Name="dbo.GoiChoi" Member="GoiChois">
    <Type Name="GoiChoi">
      <Column Name="MaGoi" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenGoi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaTien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="GoiChoi_ListSP" Member="ListSPs" ThisKey="MaGoi" OtherKey="MaMonAn" Type="ListSP" />
    </Type>
  </Table>
  <Table Name="dbo.ListSP" Member="ListSPs">
    <Type Name="ListSP">
      <Column Name="[ID San Pham]" Member="ID_San_Pham" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaMonAn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaDoUong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaGoiChoi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DoUong_ListSP" Member="DoUong" ThisKey="MaDoUong" OtherKey="MaDoUong" Type="DoUong" IsForeignKey="true" />
      <Association Name="GoiChoi_ListSP" Member="GoiChoi" ThisKey="MaMonAn" OtherKey="MaGoi" Type="GoiChoi" IsForeignKey="true" />
      <Association Name="MonAn_ListSP" Member="MonAn" ThisKey="MaMonAn" OtherKey="MaMonAn" Type="MonAn" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MonAn" Member="MonAns">
    <Type Name="MonAn">
      <Column Name="MaMonAn" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenMonAn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaTien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="MonAn_ListSP" Member="ListSPs" ThisKey="MaMonAn" OtherKey="MaMonAn" Type="ListSP" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LoaiTaiKhoan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>